# ACCELEROMETER DATA --> Page0
ACCEL_DATA_X_LSB_ADDRESS = 0x08
ACCEL_DATA_Y_LSB_ADDRESS = 0x0A
ACCEL_DATA_Z_LSB_ADDRESS = 0x0C

# ACCELEROMETER CONFIG --> Page1
ACC_CONFIG = 0x08

# GYROSCOPE DATA --> Page0
GYRO_DATA_X_LSB_ADDRESS = 0x14
GYRO_DATA_Y_LSB_ADDRESS = 0x16
GYRO_DATA_Z_LSB_ADDRESS = 0x18

# GYROSCOPE CONFIG
GYRO_CONFIG_0 = 0x0A
GYRO_CONFIG_1 = 0x0B

# UNIT SELECTION
UNIT_SEL = 0x3B

# PAGE SELECT REGISTER
PAGE_SELECT_ADDRESS = 0x07

# POWER MODE
PWR_MODE_ADDRESS = 0x3E

# OPERATION MODE
OP_MODE_ADDRESS = 0x3D

# SYSTEM STATUS
SYS_STATUS_ADDRESS = 0x39

# SYSTEM ERROR
SYS_ERR_ADDRESS = 0x3A

# CALIBRATION STATUS
CALIB_STAT_ADDRESS = 0x35
